/* ─────────────────────────────────────────────────────────────────────────────
   Firebase Configuration Template
   ─────────────────────────────────────────────────────────────────────────────
   DO NOT edit this file with real values — it is committed to git.
   Real credentials are injected by GitHub Actions from repository secrets.

   LOCAL DEVELOPMENT:
   Copy this file to firebase-config.js and fill in your real values:
     cp firebase-config.template.js firebase-config.js
   firebase-config.js is gitignored and will never be committed.

   GITHUB ACTIONS:
   Add these secrets in your repo → Settings → Secrets and variables → Actions:
     FIREBASE_API_KEY
     FIREBASE_AUTH_DOMAIN
     FIREBASE_PROJECT_ID
     FIREBASE_STORAGE_BUCKET
     FIREBASE_MESSAGING_SENDER_ID
     FIREBASE_APP_ID
   ─────────────────────────────────────────────────────────────────────────────*/

const firebaseConfig = {
  apiKey:            "AIzaSyBIvAKp6qo4MF0CJdAeEGKdb2_C1kDfrCI",
  authDomain:        "finance-tracker-ed12f.firebaseapp.com",
  projectId:         "finance-tracker-ed12f",
  storageBucket:     "finance-tracker-ed12f.firebasestorage.app",
  messagingSenderId: "614843668620",
  appId:             "1:614843668620:web:f3b3b397c99d2e804083a9",
};

// ── Initialize Firebase ───────────────────────────────────────────────────────
firebase.initializeApp(firebaseConfig);

/** Shared Firebase Auth instance */
const fbAuth = firebase.auth();

/** Shared Firestore instance */
const fbDb = firebase.firestore();

// Enable offline persistence so the app works without internet after first login
fbDb.enablePersistence({ synchronizeTabs: true }).catch(err => {
  if (err.code === 'failed-precondition') {
    console.warn('Firestore persistence disabled: multiple tabs open simultaneously.');
  } else if (err.code === 'unimplemented') {
    console.warn('Firestore persistence not supported in this browser.');
  }
});
